config/routes.rb
Rails.application.routes.draw do

  resources :categories

  root 'static#newv2_walls'

  get 'work' => 'static#artwork'
  get 'contact' => 'static#contact'
  get 'instagram' => 'static#instagram'

  scope "/admin" do

    resources :users
    
    resources :artworks do
      collection do
        post :sort
      end
    end

    resources :walls do
      collection do
        post :sort
      end
    end

    resources :blogs do
      collection do
        post :sort
      end
    end
    
  end

  get '/walls' => 'static#walls'
  get '/walls2' => 'static#newv2_walls'
  get '/admin' => 'static#admin'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  
  has_secure_password
  
  has_many :blogs
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to users_url, notice: "User #{@user.name} was successfully created."
    else
      render action: "new"
    end
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to users_url, notice: "User #{@user.name} was successfully updated."
    else
      render action: "edit"
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User deleted'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  %fieldset    
    .field
      = f.label :name
      = f.text_field :name
    .field
      = f.label :password
      = f.password_field :password
    .field
      = f.label :password_confirmation, 'Confirm'
      = f.password_field :password_confirmation
  .actions
    = link_to 'Back', users_path
    = f.submit class: 'btn'

app/views/users/edit.html.haml
%section.admin
  %h1 edit user
  = render 'form'

app/views/users/index.html.haml
%section.admin

  %h1 listing users

  %table.admintable
    %thead
      %tr
        %th Name
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= user.name
          %td{ class: 'actions' }
            = link_to 'Edit', edit_user_path(user)
            = link_to 'Destroy', user, method: :delete, class: "delete_btn", data: {confirm: 'Are you sure?'}, class: 'delete'

  .actions
    = link_to 'Back', admin_path
    = link_to 'New User', new_user_path

app/views/users/new.html.haml
%section.admin
  %h1 new user
  = render 'form'