config/routes.rb
Rails.application.routes.draw do

  resources :categories

  root 'static#newv2_walls'

  get 'work' => 'static#artwork'
  get 'contact' => 'static#contact'
  get 'instagram' => 'static#instagram'

  scope "/admin" do

    resources :users
    
    resources :artworks do
      collection do
        post :sort
      end
    end

    resources :walls do
      collection do
        post :sort
      end
    end

    resources :blogs do
      collection do
        post :sort
      end
    end
    
  end

  get '/walls' => 'static#walls'
  get '/walls2' => 'static#newv2_walls'
  get '/admin' => 'static#admin'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

end

app/models/wall.rb
class Wall < ActiveRecord::Base

  validates :title, :image, presence: true

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

  after_update :crop_avatar

  mount_uploader :image, JerkfaceUploader

  def crop_avatar
    image.recreate_versions! if crop_x.present?
  end
  
end

app/controllers/walls_controller.rb
class WallsController < ApplicationController
  before_action :set_wall, only: [:show, :edit, :update, :destroy]

  # GET /walls
  def index
    @walls = Wall.all
  end


  # GET /walls/new
  def new
    @wall = Wall.new
  end

  # GET /walls/1/edit
  def edit
  end

  # POST /walls
  def create
    @wall = Wall.new(wall_params)
    if @wall.save
      if params[:wall][:image]
        render :crop
      else
        redirect_to walls_url, notice: 'Wall successfully created.'
      end
    else
      render :new
    end
  end

  # PATCH/PUT /walls/1
  def update
    if @wall.update(wall_params)
      redirect_to walls_url, notice: 'Wall was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /walls/1
  def destroy
    @wall.destroy
    redirect_to walls_url, notice: 'Wall was successfully destroyed.'
  end

  def sort
    params[:wall].each_with_index do |id, index|
      Wall.where(id: id).update_all(position: index+1)
    end
    render nothing: true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wall
      @wall = Wall.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def wall_params
      params.require(:wall).permit(:title, :year, :image, :location, :position, :crop_x, :crop_y, :crop_w, :crop_h)
    end
end

app/views/walls/_form.html.haml
= form_for(@wall) do |f|
  - if @wall.errors.any?
    #error_explanation
      %h2
        = pluralize(@wall.errors.count, "error")
        prohibited this wall from being saved:
      %ul
        - @wall.errors.full_messages.each do |msg|
          %li= msg

  %fieldset      
    .field
      = f.label :title
      = f.text_field :title
    .field
      = f.label :location
      = f.text_field :location
    .field
      = f.label :year
      = f.select :year, (Time.now.year-3..Time.now.year).to_a.reverse, { prompt: false }
    .field
      = f.label :image
      = f.file_field :image
  .actions
    = link_to 'Back', walls_path
    = f.submit

app/views/walls/crop.html.haml
%section.admin

  %h1 Create Thumbnail

  .crop-holder
    = image_tag @wall.image_url(:large), id: "cropbox"

  = form_for @wall do |f|
    - %w[x y w h].each do |attribute|
      = f.hidden_field "crop_#{attribute}"

    .actions
      = f.submit "Crop", class: 'btn'

app/views/walls/edit.html.haml
%section.admin
  %h1 Editing Wall
  = render 'form'

app/views/walls/index.html.haml
%section.admin
  %h1 Listing Walls

  %table
    %thead
      %tr
        %th
        %th Title
        %th.year Year
        %th.location Location
        %th
    %tbody.sorts{ data: { update_url: sort_walls_url } }
      - @walls.each do |wall|
        = content_tag_for :tr, wall do
          %td.img= image_tag wall.image_url(:icon).to_s
          %td= wall.title
          %td.year= wall.year
          %td.location= wall.location
          %td.actions
            = link_to 'Edit', edit_wall_path(wall)
            = link_to 'Destroy', wall, method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete'

  .actions
    = link_to 'Back', admin_path
    = link_to 'New wall', new_wall_path

app/views/walls/new.html.haml
%section.admin
  %h1 New Wall
  = render 'form'