config/routes.rb
Rails.application.routes.draw do

  resources :categories

  root 'static#newv2_walls'

  get 'work' => 'static#artwork'
  get 'contact' => 'static#contact'
  get 'instagram' => 'static#instagram'

  scope "/admin" do

    resources :users
    
    resources :artworks do
      collection do
        post :sort
      end
    end

    resources :walls do
      collection do
        post :sort
      end
    end

    resources :blogs do
      collection do
        post :sort
      end
    end
    
  end

  get '/walls' => 'static#walls'
  get '/walls2' => 'static#newv2_walls'
  get '/admin' => 'static#admin'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_many :artworks

  def name
    width.to_s + 'x' +height.to_s
  end

  def area
    width * height
  end

  before_destroy :ensure_category_has_no_artwork

  private
  
  def ensure_category_has_no_artwork
    if artworks.empty?
      return true 
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    @categories = Category.all.sort_by(&:area)
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_url, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to categories_url, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(:width, :height, :show)
    end
end

app/views/categories/_form.html.haml
= form_for(@category) do |f|
  - if @category.errors.any?
    #error_explanation
      %h2
        = pluralize(@category.errors.count, "error")
        prohibited this category from being saved:
      %ul
        - @category.errors.full_messages.each do |message|
          %li= message


  %fieldset
    .field
      = f.label :width
      = f.text_field :width
    .field
      = f.label :height
      = f.text_field :height
    .field.checkbox
      = f.label :show
      = f.check_box :show

  .actions
    = link_to 'Back', categories_path
    = f.submit

app/views/categories/edit.html.haml
%section.admin
  %h1 Editing Category
  = render 'form'

app/views/categories/index.html.haml
%section.admin
  %h1 Listing Categories

  %table
    %tbody
      - @categories.each do |category|
        %tr{class: ("gray" unless category.show?)}
          %td= category.name
          %td.actions
            = link_to 'Edit', edit_category_path(category)
            = link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete'

  .actions
    = link_to 'Back', admin_path
    = link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%section.admin
  %h1 New Category
  = render 'form'