config/routes.rb
Rails.application.routes.draw do

  resources :categories

  root 'static#newv2_walls'

  get 'work' => 'static#artwork'
  get 'contact' => 'static#contact'
  get 'instagram' => 'static#instagram'

  scope "/admin" do

    resources :users
    
    resources :artworks do
      collection do
        post :sort
      end
    end

    resources :walls do
      collection do
        post :sort
      end
    end

    resources :blogs do
      collection do
        post :sort
      end
    end
    
  end

  get '/walls' => 'static#walls'
  get '/walls2' => 'static#newv2_walls'
  get '/admin' => 'static#admin'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

end

app/views/layouts/application.html.haml
!!! 5
%html

  %head

    %title Jerkface v2.5
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag :modernizr
    = csrf_meta_tags 
    %meta{ name: 'viewport', content: 'initial-scale=1, user-scalable=no' }

  %body
    .container{ role: 'main'}

      %header.header
        %h1.nav-link.no-slash= link_to 'Jerkface', root_url, class: cp(root_url)
        %nav.nav
          %ul#nav-list
            / %li.nav-link= link_to 'Home', root_url, class: cp(root_url)
            / %li.nav-link= link_to 'Work', work_path, class: cp(work_path)
            / %li.nav-link= link_to 'Walls', '/walls', class: cp('/walls')
            / %li.nav-link= link_to 'Instagram', instagram_path, class: cp(instagram_path)
            / / %li.nav-link= link_to 'Contact', contact_path, class: cp(contact_path)
            / %li.nav-link= link_to 'Instagram', instagram_path, class: cp(instagram_path)
            / %li.nav-link= link_to 'Contact', contact_path, class: cp(contact_path)
            -# %a{ href: '/contact'}
            -#   %img.nav-link{ src: 'https://s3.amazonaws.com/jerkfacev2/static/contact.svg'}
            %a{ href: 'https://www.instagram.com/incarceratedjerkfaces/'}
              %img.nav-link{ src: 'https://s3.amazonaws.com/jerkfacev2/static/insta.svg'}
            - if session[:user_id]
              %li.nav-link= link_to 'Admin', admin_path, class: cp(admin_path)

      .content(data-pjax-container)
        - if notice
          %p.notice= notice
        = yield

    = javascript_include_tag 'application'